# Generated by Django 4.2.23 on 2025-11-22 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(help_text='Format: YYXX (Year + Sequence)', max_length=4, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('given_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, help_text='Letter followed by period (e.g. X.)', max_length=2, null=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('schedule_day', models.DateField()),
                ('trip_cost', models.IntegerField(default=0)),
                ('trip_type', models.CharField(choices=[('L', 'Local'), ('I', 'Inter-town')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('trip_date', models.DateField()),
                ('total_cost', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='home.customer')),
                ('trips', models.ManyToManyField(related_name='tickets', to='home.trip')),
            ],
        ),
    ]
