# Generated by Django 4.2.23 on 2026-02-17 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew_In_Charge',
            fields=[
                ('employee_id', models.CharField(help_text='Format: 6 Digits (000000-999999)', max_length=6, primary_key=True, serialize=False)),
                ('first_initial', models.CharField(help_text='Letter followed by a period (e.g. X.)', max_length=2)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Log_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(help_text='Format: 6 Digits (000000-999999)', max_length=6, primary_key=True, serialize=False)),
                ('route_type', models.CharField(choices=[('L', 'Local'), ('I', 'Inter-town')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(help_text='Format: 6 Digits (000000-999999)', max_length=6, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=100)),
                ('station_type', models.CharField(choices=[('L', 'Local'), ('I', 'Inter-town')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.CharField(help_text='Format: 6 Digits (000000-999999)', max_length=6, primary_key=True, serialize=False)),
                ('train_number', models.CharField(help_text='Format: 5 Digits (00000-99999)', max_length=5, unique=True)),
                ('train_series', models.CharField(choices=[('S', 'S-Series (Western Woods)'), ('A', 'A-Series (Inter-town)')], max_length=1)),
                ('has_vending_machines', models.BooleanField(default=False)),
                ('has_food_service', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Train_Model',
            fields=[
                ('model_name', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('max_speed', models.IntegerField(blank=True, help_text='Speed in kph', null=True)),
                ('seat_capacity', models.IntegerField(default=0)),
                ('toilet_capacity', models.IntegerField(default=0)),
                ('has_reclining_seats', models.BooleanField(default=False)),
                ('has_folding_tables', models.BooleanField(default=False)),
                ('has_disability_access', models.BooleanField(default=False)),
                ('has_luggage_storage', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['departure_time']},
        ),
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.DurationField(blank=True, help_text='Auto-calculated on save', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, help_text='Format: 4 Digits (0000-9999). First 2 digits must match birth year. Auto-generated.', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(editable=False, help_text='Format: YYYYMMDDXXXX (Auto-generated)', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_cost',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(help_text='Format: YYYYMMDDXXXX', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='A_Series',
            fields=[
                ('train', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='a_series_info', serialize=False, to='home.train')),
            ],
        ),
        migrations.CreateModel(
            name='I_Route',
            fields=[
                ('i_route_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='intertown_route_info', serialize=False, to='home.route')),
            ],
        ),
        migrations.CreateModel(
            name='I_Station',
            fields=[
                ('i_station_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='intertown_info', serialize=False, to='home.station')),
            ],
        ),
        migrations.CreateModel(
            name='L_Route',
            fields=[
                ('l_route_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='local_route_info', serialize=False, to='home.route')),
            ],
        ),
        migrations.CreateModel(
            name='L_Station',
            fields=[
                ('l_station_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='local_info', serialize=False, to='home.station')),
            ],
        ),
        migrations.CreateModel(
            name='S_Series',
            fields=[
                ('train', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='s_series_info', serialize=False, to='home.train')),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='train_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trains', to='home.train_model'),
        ),
        migrations.CreateModel(
            name='Maintenance_Log',
            fields=[
                ('log_id', models.CharField(editable=False, help_text='Format: YYYYMMDDXXXX (Auto-generated)', max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20)),
                ('crew_in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='home.crew_in_charge')),
                ('tasks', models.ManyToManyField(related_name='maintenance_logs', through='home.Log_Task', to='home.task')),
                ('train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='home.train')),
            ],
        ),
        migrations.AddField(
            model_name='log_task',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_tasks', to='home.maintenance_log'),
        ),
        migrations.AddField(
            model_name='log_task',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='home.task'),
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='home.route'),
        ),
        migrations.AddField(
            model_name='trip',
            name='train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='home.train'),
        ),
        migrations.AlterUniqueTogether(
            name='log_task',
            unique_together={('log', 'task')},
        ),
        migrations.CreateModel(
            name='L_Trip',
            fields=[
                ('l_trip_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='local_trip_info', serialize=False, to='home.trip')),
                ('l_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_trips', to='home.l_route')),
                ('s_train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_trips', to='home.s_series')),
            ],
        ),
        migrations.AddField(
            model_name='l_route',
            name='l_route_desti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_ending_here', to='home.l_station'),
        ),
        migrations.AddField(
            model_name='l_route',
            name='l_route_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_starting_here', to='home.l_station'),
        ),
        migrations.CreateModel(
            name='I_Trip',
            fields=[
                ('i_trip_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='intertown_trip_info', serialize=False, to='home.trip')),
                ('a_train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intertown_trips', to='home.a_series')),
                ('i_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intertown_trips', to='home.i_route')),
            ],
        ),
        migrations.AddField(
            model_name='i_route',
            name='i_route_desti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_ending_here', to='home.i_station'),
        ),
        migrations.AddField(
            model_name='i_route',
            name='i_route_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_starting_here', to='home.i_station'),
        ),
    ]
