# Generated by Django 4.2.23 on 2026-02-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_crew_in_charge_log_task_route_station_task_train_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='True if trip has concluded'),
        ),
        migrations.AlterField(
            model_name='log_task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
